/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ComplianceLibraryRouteImport } from './routes/compliance-library'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HelpRouteImport } from './routes/help'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RiskAssessmentRouteImport } from './routes/risk-assessment'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAuditLogsRouteImport } from './routes/_app.audit-logs'
import { Route as AppEvidenceRouteImport } from './routes/_app.evidence'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppComplaintsIndexRouteImport } from './routes/_app.complaints.index'
import { Route as AppComplaintsComplaintIdRouteImport } from './routes/_app.complaints.$complaintId'
import { Route as AppComplaintsNewRouteImport } from './routes/_app.complaints.new'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app.departments.index'
import { Route as AppDepartmentsDepartmentIdRouteImport } from './routes/_app.departments.$departmentId'
import { Route as AppInvestigationsIndexRouteImport } from './routes/_app.investigations.index'
import { Route as AppInvestigationsInvestigationIdRouteImport } from './routes/_app.investigations.$investigationId'
import { Route as AppRisksIndexRouteImport } from './routes/_app.risks.index'
import { Route as AppRisksRiskIdRouteImport } from './routes/_app.risks.$riskId'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app.users.$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceLibraryRoute = ComplianceLibraryRouteImport.update({
  id: '/compliance-library',
  path: '/compliance-library',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAssessmentRoute = RiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditLogsRoute = AppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsIndexRoute = AppComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsComplaintIdRoute =
  AppComplaintsComplaintIdRouteImport.update({
    id: '/complaints/$complaintId',
    path: '/complaints/$complaintId',
    getParentRoute: () => AppRoute,
  } as any)
const AppComplaintsNewRoute = AppComplaintsNewRouteImport.update({
  id: '/complaints/new',
  path: '/complaints/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsDepartmentIdRoute =
  AppDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInvestigationsIndexRoute = AppInvestigationsIndexRouteImport.update({
  id: '/investigations/',
  path: '/investigations/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvestigationsInvestigationIdRoute =
  AppInvestigationsInvestigationIdRouteImport.update({
    id: '/investigations/$investigationId',
    path: '/investigations/$investigationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppRisksIndexRoute = AppRisksIndexRouteImport.update({
  id: '/risks/',
  path: '/risks/',
  getParentRoute: () => AppRoute,
} as any)
const AppRisksRiskIdRoute = AppRisksRiskIdRouteImport.update({
  id: '/risks/$riskId',
  path: '/risks/$riskId',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/compliance-library': typeof ComplianceLibraryRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/partners': typeof PartnersRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/evidence': typeof AppEvidenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/investigations/$investigationId': typeof AppInvestigationsInvestigationIdRoute
  '/risks/$riskId': typeof AppRisksRiskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/complaints/': typeof AppComplaintsIndexRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/investigations/': typeof AppInvestigationsIndexRoute
  '/risks/': typeof AppRisksIndexRoute
  '/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/compliance-library': typeof ComplianceLibraryRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/partners': typeof PartnersRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit-logs': typeof AppAuditLogsRoute
  '/evidence': typeof AppEvidenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/complaints/new': typeof AppComplaintsNewRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/investigations/$investigationId': typeof AppInvestigationsInvestigationIdRoute
  '/risks/$riskId': typeof AppRisksRiskIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/complaints': typeof AppComplaintsIndexRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/investigations': typeof AppInvestigationsIndexRoute
  '/risks': typeof AppRisksIndexRoute
  '/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/api-reference': typeof ApiReferenceRoute
  '/careers': typeof CareersRoute
  '/compliance-library': typeof ComplianceLibraryRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/features': typeof FeaturesRoute
  '/guides': typeof GuidesRoute
  '/help': typeof HelpRoute
  '/partners': typeof PartnersRoute
  '/resources': typeof ResourcesRoute
  '/risk-assessment': typeof RiskAssessmentRoute
  '/security': typeof SecurityRoute
  '/signin': typeof SigninRoute
  '/solutions': typeof SolutionsRoute
  '/status': typeof StatusRoute
  '/templates': typeof TemplatesRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit-logs': typeof AppAuditLogsRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/complaints/$complaintId': typeof AppComplaintsComplaintIdRoute
  '/_app/complaints/new': typeof AppComplaintsNewRoute
  '/_app/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/_app/investigations/$investigationId': typeof AppInvestigationsInvestigationIdRoute
  '/_app/risks/$riskId': typeof AppRisksRiskIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/complaints/': typeof AppComplaintsIndexRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/investigations/': typeof AppInvestigationsIndexRoute
  '/_app/risks/': typeof AppRisksIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/compliance-library'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/guides'
    | '/help'
    | '/partners'
    | '/resources'
    | '/risk-assessment'
    | '/security'
    | '/signin'
    | '/solutions'
    | '/status'
    | '/templates'
    | '/analytics'
    | '/audit-logs'
    | '/evidence'
    | '/notifications'
    | '/settings'
    | '/complaints/$complaintId'
    | '/complaints/new'
    | '/departments/$departmentId'
    | '/investigations/$investigationId'
    | '/risks/$riskId'
    | '/users/$userId'
    | '/complaints/'
    | '/departments/'
    | '/investigations/'
    | '/risks/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/compliance-library'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/guides'
    | '/help'
    | '/partners'
    | '/resources'
    | '/risk-assessment'
    | '/security'
    | '/signin'
    | '/solutions'
    | '/status'
    | '/templates'
    | '/analytics'
    | '/audit-logs'
    | '/evidence'
    | '/notifications'
    | '/settings'
    | '/complaints/$complaintId'
    | '/complaints/new'
    | '/departments/$departmentId'
    | '/investigations/$investigationId'
    | '/risks/$riskId'
    | '/users/$userId'
    | '/complaints'
    | '/departments'
    | '/investigations'
    | '/risks'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/api-reference'
    | '/careers'
    | '/compliance-library'
    | '/contact'
    | '/dashboard'
    | '/docs'
    | '/features'
    | '/guides'
    | '/help'
    | '/partners'
    | '/resources'
    | '/risk-assessment'
    | '/security'
    | '/signin'
    | '/solutions'
    | '/status'
    | '/templates'
    | '/_app/analytics'
    | '/_app/audit-logs'
    | '/_app/evidence'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/complaints/$complaintId'
    | '/_app/complaints/new'
    | '/_app/departments/$departmentId'
    | '/_app/investigations/$investigationId'
    | '/_app/risks/$riskId'
    | '/_app/users/$userId'
    | '/_app/complaints/'
    | '/_app/departments/'
    | '/_app/investigations/'
    | '/_app/risks/'
    | '/_app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  CareersRoute: typeof CareersRoute
  ComplianceLibraryRoute: typeof ComplianceLibraryRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FeaturesRoute: typeof FeaturesRoute
  GuidesRoute: typeof GuidesRoute
  HelpRoute: typeof HelpRoute
  PartnersRoute: typeof PartnersRoute
  ResourcesRoute: typeof ResourcesRoute
  RiskAssessmentRoute: typeof RiskAssessmentRoute
  SecurityRoute: typeof SecurityRoute
  SigninRoute: typeof SigninRoute
  SolutionsRoute: typeof SolutionsRoute
  StatusRoute: typeof StatusRoute
  TemplatesRoute: typeof TemplatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-library': {
      id: '/compliance-library'
      path: '/compliance-library'
      fullPath: '/compliance-library'
      preLoaderRoute: typeof ComplianceLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-assessment': {
      id: '/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/risk-assessment'
      preLoaderRoute: typeof RiskAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-logs': {
      id: '/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AppAuditLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/': {
      id: '/_app/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AppComplaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/$complaintId': {
      id: '/_app/complaints/$complaintId'
      path: '/complaints/$complaintId'
      fullPath: '/complaints/$complaintId'
      preLoaderRoute: typeof AppComplaintsComplaintIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints/new': {
      id: '/_app/complaints/new'
      path: '/complaints/new'
      fullPath: '/complaints/new'
      preLoaderRoute: typeof AppComplaintsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments/$departmentId': {
      id: '/_app/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof AppDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations/': {
      id: '/_app/investigations/'
      path: '/investigations'
      fullPath: '/investigations/'
      preLoaderRoute: typeof AppInvestigationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/investigations/$investigationId': {
      id: '/_app/investigations/$investigationId'
      path: '/investigations/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof AppInvestigationsInvestigationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risks/': {
      id: '/_app/risks/'
      path: '/risks'
      fullPath: '/risks/'
      preLoaderRoute: typeof AppRisksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risks/$riskId': {
      id: '/_app/risks/$riskId'
      path: '/risks/$riskId'
      fullPath: '/risks/$riskId'
      preLoaderRoute: typeof AppRisksRiskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditLogsRoute: typeof AppAuditLogsRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppComplaintsComplaintIdRoute: typeof AppComplaintsComplaintIdRoute
  AppComplaintsNewRoute: typeof AppComplaintsNewRoute
  AppDepartmentsDepartmentIdRoute: typeof AppDepartmentsDepartmentIdRoute
  AppInvestigationsInvestigationIdRoute: typeof AppInvestigationsInvestigationIdRoute
  AppRisksRiskIdRoute: typeof AppRisksRiskIdRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppComplaintsIndexRoute: typeof AppComplaintsIndexRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppInvestigationsIndexRoute: typeof AppInvestigationsIndexRoute
  AppRisksIndexRoute: typeof AppRisksIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditLogsRoute: AppAuditLogsRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppComplaintsComplaintIdRoute: AppComplaintsComplaintIdRoute,
  AppComplaintsNewRoute: AppComplaintsNewRoute,
  AppDepartmentsDepartmentIdRoute: AppDepartmentsDepartmentIdRoute,
  AppInvestigationsInvestigationIdRoute: AppInvestigationsInvestigationIdRoute,
  AppRisksRiskIdRoute: AppRisksRiskIdRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppComplaintsIndexRoute: AppComplaintsIndexRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppInvestigationsIndexRoute: AppInvestigationsIndexRoute,
  AppRisksIndexRoute: AppRisksIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  CareersRoute: CareersRoute,
  ComplianceLibraryRoute: ComplianceLibraryRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FeaturesRoute: FeaturesRoute,
  GuidesRoute: GuidesRoute,
  HelpRoute: HelpRoute,
  PartnersRoute: PartnersRoute,
  ResourcesRoute: ResourcesRoute,
  RiskAssessmentRoute: RiskAssessmentRoute,
  SecurityRoute: SecurityRoute,
  SigninRoute: SigninRoute,
  SolutionsRoute: SolutionsRoute,
  StatusRoute: StatusRoute,
  TemplatesRoute: TemplatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
